"""
Parses markdown trading reports into structured ParsedDecisions.

PRD §9 — parser extracts only agent_rating/allocation_pct/leverage/
short_allowed/stop_price/take_profit. NO action inference.
futures_action is generated by DecisionStateManager, not the parser.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from .decision_schema import Rating
from .position import ExtendedDecision, ParsedDecision


class MarkdownDecisionParser:
    RATING_PATTERN = re.compile(
        r"\b(Sell|Buy|Hold|WNS|Wait\s+and\s+See|Wait-and-See|Underweight|Overweight"
        r"|Jual|Beli|Tahan)\b",
        re.IGNORECASE,
    )

    def parse_file(
        self,
        path: str | Path,
        fallback_ticker: Optional[str] = None,
        fallback_trade_date: Optional[str] = None,
        fallback_decision_valid_from: Optional[str] = None,
    ) -> ExtendedDecision:
        p = Path(path)
        text = p.read_text(encoding="utf-8")
        return self.parse_text(
            text=text,
            source_report_path=str(p),
            fallback_ticker=fallback_ticker,
            fallback_trade_date=fallback_trade_date,
            fallback_decision_valid_from=fallback_decision_valid_from,
        )

    def parse_text(
        self,
        text: str,
        source_report_path: Optional[str] = None,
        fallback_ticker: Optional[str] = None,
        fallback_trade_date: Optional[str] = None,
        fallback_decision_valid_from: Optional[str] = None,
    ) -> ExtendedDecision:
        ticker = self._extract_ticker(text) or fallback_ticker

        generated_at = self._extract_metadata(text, "Generated")
        trade_date = (
            self._extract_metadata(text, "Trade Date")
            or self._extract_report_date(text)
            or fallback_trade_date
        )
        last_data_date = (
            self._extract_metadata(text, "Last Data Date")
            or self._extract_last_trading_day(text)
            or trade_date
        )
        decision_valid_from = (
            self._extract_metadata(text, "Decision Valid From")
            or fallback_decision_valid_from
        )

        if not ticker or not trade_date:
            return ExtendedDecision.invalid(
                ticker=ticker or "UNKNOWN",
                trade_date=trade_date or "UNKNOWN",
                reason="Missing ticker or trade_date in report.",
                source_report_path=source_report_path,
            )

        if not generated_at:
            generated_at = f"{trade_date} 16:30:00"
        if not last_data_date:
            last_data_date = trade_date

        if not decision_valid_from:
            return ExtendedDecision.invalid(
                ticker=ticker,
                trade_date=trade_date,
                reason="Missing Decision Valid From. Refuse trading to avoid same-bar execution.",
                source_report_path=source_report_path,
            )

        agent_rating = self._extract_rating(text)
        if agent_rating == Rating.INVALID:
            return ExtendedDecision.invalid(
                ticker=ticker,
                trade_date=trade_date,
                reason="Unable to parse one of: Sell, Buy, Hold, Underweight, Overweight.",
                source_report_path=source_report_path,
            )

        normalized_rating = agent_rating.value.upper()

        confidence = self._extract_pct(
            text,
            patterns=[
                r"\*{0,2}confidence\*{0,2}\s*[:=]\s*\*{0,2}(\d+(?:\.\d+)?)",
                r"\*{0,2}keyakinan\*{0,2}\s*[:=]\s*\*{0,2}(\d+(?:\.\d+)?)",
            ],
            normalize_to_fraction=True,
        )

        allocation_pct = self._extract_pct(
            text,
            patterns=[
                r"target[_\s-]*position[_\s-]*pct\s*[:=]\s*(\d+(?:\.\d+)?)",
                r"target\s+position\s*[:=]?\s*(\d+(?:\.\d+)?)\s*%",
                r"alokasi\s*(\d+(?:\.\d+)?)\s*%",
                r"allocation\s*[:=]\s*(\d+(?:\.\d+)?)",
            ],
        )

        reduce_pct = self._extract_pct(
            text,
            patterns=[
                r"initial[_\s-]*trim[_\s-]*pct\s*[:=]\s*(\d+(?:\.\d+)?)",
                r"trim\s+awal\s*(\d+(?:\.\d+)?)\s*%",
                r"reduce[_\s-]*pct\s*[:=]\s*(\d+(?:\.\d+)?)",
                r"[Rr]educe\s*[:=]?\s*(\d+(?:\.\d+)?)\s*%",
            ],
        )

        leverage = self._extract_int(
            text,
            patterns=[
                r"leverage\s*[:=]\s*(\d+)",
                r"lever\s*[:=]\s*(\d+)",
            ],
        )

        stop_price = self._extract_float(
            text,
            patterns=[
                r"(?:stop[_\s-]*(?:loss|price)?)\s*\*{0,2}\s*[:=]\s*\*{0,2}\s*(\d+(?:\.\d+)?)",
                r"stop\s+di\s*(\d+(?:\.\d+)?)",
                r"cut\s+loss\s*[:=]?\s*(\d+(?:\.\d+)?)",
            ],
        )

        take_profit = self._extract_float(
            text,
            patterns=[
                r"(?:take[_\s-]*profit|target)\s*\*{0,2}\s*[:=]\s*\*{0,2}\s*(\d+(?:\.\d+)?)",
                r"target\s+harga\s*[:=]?\s*(\d+(?:\.\d+)?)",
            ],
        )

        planned_entry_price = self._extract_float(
            text,
            patterns=[
                r"(?:planned[_\s-]*entry[_\s-]*(?:price)?|entry[_\s-]*price)\s*\*{0,2}\s*[:=]\s*\*{0,2}\s*(\d+(?:\.\d+)?)",
                r"harga\s+masuk\s*[:=]?\s*(\d+(?:\.\d+)?)",
                r"entry\s+di\s*(\d+(?:\.\d+)?)",
            ],
        )

        wns_trigger_price = self._extract_float(
            text,
            patterns=[
                r"wns[_\s-]*trigger[_\s-]*price\s*\*{0,2}\s*[:=]\s*\*{0,2}\s*(\d+(?:\.\d+)?)",
                r"trigger[_\s-]*price\s*\*{0,2}\s*[:=]\s*\*{0,2}\s*(\d+(?:\.\d+)?)",
                r"touch\s+(?:price\s+level\s+)?(\d+(?:\.\d+)?)",
            ],
        )

        wns_recheck_date = self._extract_text(
            text,
            patterns=[
                r"wns[_\s-]*recheck[_\s-]*date\s*\*{0,2}\s*[:=]\s*\*{0,2}(\d{4}-\d{2}-\d{2})",
                r"recheck[_\s-]*date\s*\*{0,2}\s*[:=]\s*\*{0,2}(\d{4}-\d{2}-\d{2})",
                r"check\s+after\s+(?:date\s+)?(\d{4}-\d{2}-\d{2})",
            ],
        )

        time_horizon_label = self._extract_text(
            text,
            patterns=[
                r"\*{0,2}time[_\s-]*horizon\*{0,2}\s*[:=]\s*\*{0,2}(.+?)\*{0,2}\s*$",
                r"\*{0,2}holding[_\s-]*period\*{0,2}\s*[:=]\s*\*{0,2}(.+?)\*{0,2}\s*$",
            ],
        )
        time_horizon_days = self._extract_int(
            text,
            patterns=[
                r"\*{0,2}time[_\s-]*horizon[_\s-]*days\*{0,2}\s*[:=]\s*\*{0,2}(\d+)",
                r"horizon\s*(\d+)\s*hari",
            ],
        )
        if time_horizon_days is None:
            time_horizon_days = self._upper_bound_horizon_days(time_horizon_label)

        short_allowed = True
        if re.search(
            r"(jangan|tidak|no|don't)\s+(?:buka\s+posisi\s+)?(short|jual\s+pendek)",
            text,
            re.I,
        ):
            short_allowed = False

        allow_new_position = True
        if re.search(
            r"(jangan|tidak)\s+(buka|entry|buy|beli|short).{0,40}(posisi|position)",
            text,
            re.I,
        ):
            allow_new_position = False

        market_mode = self._extract_market_mode(text)
        allowed_sides = self._extract_allowed_sides(text)
        next_review_date = self._extract_next_review_date(text)

        decision_id = f"{ticker}-{trade_date}"
        return ExtendedDecision(
            decision_id=decision_id,
            ticker=ticker,
            trade_date=trade_date,
            report_generated_at=generated_at,
            last_data_date=last_data_date,
            decision_valid_from=decision_valid_from,
            agent_rating=agent_rating.value,
            normalized_rating=normalized_rating,
            confidence=confidence,
            allocation_pct=allocation_pct,
            reduce_pct=reduce_pct,
            leverage=leverage,
            stop_price=stop_price,
            take_profit=take_profit,
            planned_entry_price=planned_entry_price,
            wns_trigger_price=wns_trigger_price,
            wns_recheck_date=wns_recheck_date,
            time_horizon_days=time_horizon_days,
            time_horizon_label=time_horizon_label,
            allow_new_position=allow_new_position,
            short_allowed=short_allowed,
            market_mode=market_mode,
            allowed_position_sides=allowed_sides,
            source_report_path=source_report_path,
            raw_text_excerpt=text[:1000],
            next_review_date=next_review_date,
        )

    def _extract_ticker(self, text: str) -> Optional[str]:
        patterns = [
            r"Trading Analysis Report:\s*([A-Z0-9.\-]+)",
            r"Ticker\s*[:=]\s*([A-Z0-9.\-]+)",
            r"\b([A-Z]{2,5}\.JK)\b",
        ]
        for pattern in patterns:
            match = re.search(pattern, text, re.I)
            if match:
                return match.group(1).upper()
        return None

    def _extract_metadata(self, text: str, field: str) -> Optional[str]:
        pattern = rf"^{re.escape(field)}\s*:\s*(.+)$"
        match = re.search(pattern, text, re.I | re.M)
        if not match:
            return None
        return match.group(1).strip()

    def _extract_rating(self, text: str) -> Rating:
        section = self._preferred_section(text)
        match = self.RATING_PATTERN.search(section)
        if not match:
            match = self.RATING_PATTERN.search(text)
        if not match:
            return Rating.INVALID
        normalized = match.group(1).strip().lower()
        mapping = {
            "buy": Rating.BUY, "beli": Rating.BUY,
            "sell": Rating.SELL, "jual": Rating.SELL,
            "hold": Rating.HOLD, "tahan": Rating.HOLD,
            "wns": Rating.WNS, "wait and see": Rating.WNS, "wait-and-see": Rating.WNS,
            "underweight": Rating.UNDERWEIGHT,
            "overweight": Rating.OVERWEIGHT,
        }
        return mapping.get(normalized, Rating.INVALID)

    def _extract_market_mode(self, text: str) -> str:
        return "FUTURES_STYLE_SIMULATION"

    def _extract_allowed_sides(self, text: str) -> str:
        return "LONG,SHORT"

    def _preferred_section(self, text: str) -> str:
        lower = text.lower()
        markers = [
            "portfolio manager",
            "portfolio management",
            "trader agent",
            "trading plan",
            "final decision",
            "investment decision",
            "trade plan",
            "keputusan akhir",
            "rencana trading",
        ]
        starts = []
        for marker in markers:
            idx = lower.find(marker)
            if idx >= 0:
                starts.append(idx)
        if not starts:
            return text
        start = min(starts)
        return text[start : start + 2500]

    def _extract_float(self, text: str, patterns: list[str]) -> Optional[float]:
        for pattern in patterns:
            match = re.search(pattern, text, re.I)
            if match:
                return float(match.group(1))
        return None

    def _extract_int(self, text: str, patterns: list[str]) -> Optional[int]:
        value = self._extract_float(text, patterns)
        if value is None:
            return None
        return int(value)

    def _extract_text(self, text: str, patterns: list[str]) -> Optional[str]:
        for pattern in patterns:
            match = re.search(pattern, text, re.I | re.M)
            if match:
                return match.group(1).strip()
        return None

    def _upper_bound_horizon_days(self, label: Optional[str]) -> Optional[int]:
        if not label:
            return None
        match = re.search(
            r"(\d+(?:\.\d+)?)\s*(?:-|–|—|to)\s*(\d+(?:\.\d+)?)\s*"
            r"(day|days|week|weeks|month|months|year|years|hari|minggu|bulan|tahun)",
            label,
            re.I,
        )
        if not match:
            return None
        unit = match.group(3).lower()
        multiplier = {
            "day": 1, "days": 1,
            "week": 5, "weeks": 5,
            "month": 21, "months": 21,
            "year": 252, "years": 252,
            "hari": 1, "minggu": 5, "bulan": 21, "tahun": 252,
        }[unit]
        return round(float(match.group(2)) * multiplier)

    def _extract_pct(
        self,
        text: str,
        patterns: list[str],
        normalize_to_fraction: bool = False,
    ) -> Optional[float]:
        value = self._extract_float(text, patterns)
        if value is None:
            return None
        if normalize_to_fraction and value > 1:
            return value / 100.0
        return value

    def _extract_report_date(self, text: str) -> Optional[str]:
        patterns = [
            r"\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})",
            r"\bDate:\s*(\d{4}-\d{2}-\d{2})",
        ]
        for pattern in patterns:
            match = re.search(pattern, text, re.I)
            if match:
                return match.group(1)
        return None

    def _extract_last_trading_day(self, text: str) -> Optional[str]:
        patterns = [
            r"\*\*Last Trading Day:\*\*\s*(\d{4}-\d{2}-\d{2})",
            r"\bLast Trading Day:\s*(\d{4}-\d{2}-\d{2})",
            r"\bLast Data Date:\s*(\d{4}-\d{2}-\d{2})",
        ]
        for pattern in patterns:
            match = re.search(pattern, text, re.I)
            if match:
                return match.group(1)
        return None

    def _extract_next_review_date(self, text: str) -> Optional[str]:
        patterns = [
            # English bold format (same line): **Next Review Date**: 2024-02-15
            r"\*\*Next Review Date\*\*:\s*(\d{4}-\d{2}-\d{2})",
            # English plain format (same line): Next Review Date: 2024-02-15
            r"Next Review Date:\s*(\d{4}-\d{2}-\d{2})",
            # key=value format: next_review_date: 2024-02-15
            r"next[_\s-]*review[_\s-]*date\s*[:=]\s*(\d{4}-\d{2}-\d{2})",
            # Indonesian multi-line: ## TANGGAL REVIEW BERIKUTNYA\n\n**2024-02-15**
            r"(?:##\s*(?:TANGGAL|Tanggal)\s+REVIEW\s+BERIKUTNYA)\s*\n+\s*\*{0,2}(\d{4}-\d{2}-\d{2})\*{0,2}",
            # Indonesian multi-line without bold: ## Tanggal Review Berikutnya\n\n2024-02-15
            r"(?:##\s*(?:TANGGAL|Tanggal)\s+(?:REVIEW|review)\s+(?:BERIKUTNYA|berikutnya))\s*\n+\s*(\d{4}-\d{2}-\d{2})",
            # Indonesian same line: Tanggal Review Berikutnya: 2024-02-15
            r"(?:TANGGAL|Tanggal)\s+(?:REVIEW|review)\s+(?:BERIKUTNYA|berikutnya)\s*[:=]?\s*(\d{4}-\d{2}-\d{2})",
            # Generic: any line containing "review" then date
            r"(?:review|tanggal)\s*(?:berikutnya)?\s*[:=]?\s*(\d{4}-\d{2}-\d{2})",
        ]
        for pattern in patterns:
            match = re.search(pattern, text, re.I | re.M)
            if match:
                return match.group(1)
        return None
